from .bill_delivery import *
from .contract import *
from .file_manager import *
from .fund_bill import *
from .information import *
from .quality import *

BI_REQUESTS = {
    "BILL_DELIVERY_ASSIGNABLE_BILL_QUANTITY": BillDeliveryAssignableBillQuantity,
    "BILL_DELIVERY_BILL_DETAIL": BillDeliveryBillDetail,
    "BILL_DELIVERY_BILL_ISSUED_NOT_PICKUP": BillDeliveryBillIssuedNotPickup,
    "BILL_DELIVERY_BILL_NOTICE": BillDeliveryBillNotice,
    "BILL_DELIVERY_BOUND_BILL_TRANSFER_COUNT": BillDeliveryBoundBillTransferCount,
    "BILL_DELIVERY_CONTRACT_AVAILABLE_BILL": BillDeliveryContractAvailableBill,
    "BILL_DELIVERY_CONTRACT_HAS_SENT_OUT": BillDeliveryContractHasSentOut,
    "BILL_DELIVERY_CUSTOMER_AVAILABLE_BILL": BillDeliveryCustomerAvailableBill,
    "BILL_DELIVERY_DELIVERY_ORDER_STATE": BillDeliveryDeliveryOrderState,
    "BILL_DELIVERY_IN_OUT_BOUND_DATA": BillDeliveryInOutBoundData,
    "BILL_DELIVERY_LADING_BILL_STATUS_DETAIL": BillDeliveryLadingBillStatusDetail,
    "BILL_DELIVERY_LIMITED_PICKUP_PLAN_QUANTITY": BillDeliveryLimitedPickupPlanQuantity,
    "BILL_DELIVERY_LOADING_PREPARE": BillDeliveryLoadingPrepare,
    "BILL_DELIVERY_LOADING_TIME": BillDeliveryLoadingTime,
    "BILL_DELIVERY_OUTBOUND_DETAIL": BillDeliveryOutboundDetail,
    "BILL_DELIVERY_TANKER_STANDARD": BillDeliveryTankerStandard,
    "BILL_DELIVERY_VEHICLE_QUEUE_STATUS": BillDeliveryVehicleQueueStatus,
    "CONTRACT_CLOSE_DETAIL": ContractCloseDetail,
    "CONTRACT_COMPANY_DETAIL": ContractCompanyDetail,
    "CONTRACT_EXE_ORDER": ContractExeOrder,
    "CONTRACT_EXE_PROGRESS": ContractExeProgress,
    "CONTRACT_LATE_STATE": ContractLateState,
    "CONTRACT_NOT_RETURNED_LIST": ContractNotReturnedList,
    "CONTRACT_TODAY_QUOTATION": ContractTodayQuotation,
    "CONTRACT_TODAY_STATUS_DETAIL": ContractTodayStatusDetail,
    "CONTRACT_TO_BE_PAID_DETAIL": ContractToBePaidDetail,
    "FILE_COMMON_TEMPLATE": FileCommonTemplate,
    "FILE_REFUND_LETTER_TEMPLATE": FileRefundLetterTemplate,
    "FUND_BILL_ACCOUNT_AVAILABLE_PAYMENT": FundBillAccountAvailablePayment,
    "FUND_BILL_ACCOUNT_BALANCE": FundBillAccountBalance,
    "FUND_BILL_COM_BREACH_OF_CONTRACT": FundBillComBreachOfContract,
    "FUND_BILL_COM_RECEIPT_PROGRESS": FundBillComReceiptProgress,
    "FUND_BILL_CONTRACT_PAYMENT_PROGRESS": FundBillContractPaymentProgress,
    "FUND_BILL_DEPOSIT_PAYABLE": FundBillDepositPayable,
    "FUND_BILL_DEPOSIT_PAYMENT_DETAIL": FundBillDepositPaymentDetail,
    "FUND_BILL_DEPOSIT_PERF_BOND_RELEASE": FundBillDepositPerfBondRelease,
    "FUND_BILL_GOODS_PAY": FundBillGoodsPay,
    "FUND_BILL_INVOICE_HAS_BEEN_ISSUED": FundBillInvoiceHasBeenIssued,
    "FUND_BILL_ISSUED_INVOICE_DETAIL": FundBillIssuedInvoiceDetail,
    "FUND_BILL_MONTHLY_STATEMENT": FundBillMonthlyStatement,
    "FUND_BILL_NOT_ISSUED_INVOICE_DETAIL": FundBillNotIssuedInvoiceDetail,
    "FUND_BILL_PAYABLE_PAYMENT_DETAIL": FundBillPayablePaymentDetail,
    "FUND_BILL_PAYMENT_DETAIL": FundBillPaymentDetail,
    "FUND_BILL_PERFORMANCE_BOND_PAYABLE": FundBillPerformanceBondPayable,
    "FUND_BILL_TRANSFER_REQUEST_PROGRESS": FundBillTransferRequestProgress,
    "INFORMATION_COMPLAINT_PROGRESS": InformationComplaintProgress,
    "INFORMATION_CUSTOMER_GROUP": InformationCustomerGroup,
    "INFORMATION_CUSTOMER_ID": InformationCustomerId,
    "INFORMATION_CUSTOMER_PRODUCT": InformationCustomerProduct,
    "INFORMATION_CUSTOMER_STATUS": InformationCustomerStatus,
    "INFORMATION_FACTORY_MAILING_DOC_ADDRESS": InformationFactoryMailingDocAddress,
    "INFORMATION_FACTORY_PICKUP_ADDRESS": InformationFactoryPickupAddress,
    "INFORMATION_GLB_YQQ_NOT_ENABLE_LIST": InformationGlbYqqNotEnableList,
    "INFORMATION_LDCSH_RECEIVE_BANK_ACCOUNT": InformationLdcshReceiveBankAccount,
    "INFORMATION_POA_NOT_RETURN_LIST": InformationPoaNotReturnList,
    "QUALITY_QUALITY_TEST_REPORT": QualityQualityTestReport,
    "QUALITY_TEST_REPORT": QualityTestReport,
}

__all__ = ["BI_REQUESTS"]
